#!/usr/bin/python3
import os
import socket
#w overwrites, a appends
# r opens a file for writing
cmds = ["mkf: Makes a new file(be careful can overwrite with no warning if the filename exists!)",
"apf: Append to a file!",
"rfl: Read the contents of a file.",
"sysinfo: Displays useful information about the local system.",
"mdir: Makes a new directory.",
"help: Displays this help dialog listing all the commands.",
"sfile: Takes a filename and searches is for specific text. Note you may need to provide a path E.G:(if the file you are searching is not in the same directory as this program); /some/path",
"wdh: Performs a whois, dig and host lookup.",
"odh: Displays information for octal, hex, decimal",
"exit: Exits."
]
console = True
def getInfo(arg,ios):
	if ios == "str":
		return input("%s"%(arg))
	else:
		return int(input("%s" )%(arg))
def cmd(arg):
	os.system("%s"%(arg))
def mkfile():
	def fName():
		NameOk=False
		new_filename = ""
		while NameOk == False:
			new_filename = getInfo("filename please.\n$: ","str")
			if os.system("ls | grep -i '%s'"%(new_filename)) == 0:
				print("Ah a file with that name exists in this directory:\nPlease try again!")
			else:
				NameOk = True
		return new_filename
	new_file_name = fName()
	file = open(new_file_name,"w")
	print("Created a file named %s."%(new_file_name))
	file.close()
def appendFile():
	apfname = getInfo("filename please.\n$: ","str")
	tofile = getInfo("To add to the file...$: ","str")
	fileOpen = open(apfname,"a")
	fileOpen.write("\n"+tofile)
	print("Written to file...")
	fileOpen.close()
def rfile():
	fileName = getInfo("filename please.\n$: ","str")
	try:
		file = open(fileName,"r")
	except FileNotFoundError:
		print("The file you where looking for was not found...")
	file.seek(0,0)
	print(file.read())
	file.close()
def select():
	for each in cmds:
		print(each)
	return getInfo("What command please..\n$> ","str")
def sfile(filename,search):
	os.system("cat %s | grep -i %s"%(filename,search))
def wdh():
	domain = getInfo("Domain name please(just the name and the tld(e.g google.com).\n$:","str")
	std = getInfo("Would you like to save it to disk?","str")
	fileName = getInfo("Please pick a filename: \n$: ")
	if std.lower() == "yes" or std.lower() == "y":
		std = True
	else:
		std = False
	if std == False:
		print("Just getting the information...")
		cmd("whois %s"%(domain))
		cmd("dig %s"%(domain))
		cmd("host %s"%(domain))
	else:
		cmd("whois > %s"%(fileName))
		cmd("dig >> %s"%(fileName))
		cmd("host >> %s"%(fileName))
	#I know using system is back but in this context here don't think It will cause any issues(please correct me if you have a way to prove I'm wrong).
def mdir():
		dname = getInfo("Directory name please: ","str")
		cmd("mkdir %s"%(dname))
		print("OK, have made a directory called: '%s'\nPATH: %s"%(dname,os.getcwd()))
_select_ = ""
print("The current working directory is:\n%s\nOutput from the directory is:\n%s"%(os.getcwd(),cmd("ls -alt")))
while _select_ != "exit":
	try:
		_select_ = getInfo("|> ","str")
		if _select_ == "mkf":
			mkfile()
		elif _select_ == "apf":
			appendFile()
		elif _select_ == "rfl":
			rfile()
		elif _select_ == "sysinfo":
			cmd("hostnamectl")
		elif _select_ == "search":
			search(getInfo("Filename(or full path)","str"),getInfo("search terms please:\n$: ","str"))
		elif _select_ == "wdh":
				wdh()
		elif _select_ == "odh":
			os.system("man ascii")
		elif _select_ == "help":
			for each in cmds:
				print("%s\n."%(each))
	except KeyboardInterrupt:
		exit()
#socket.gethostbyname("somedomain.someld(probably t(ld)"
